name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - ipympl
